# global configs
Global:
  checkpoints: null
  pretrained_model: "E:/Prototype/PaddleClas/pretrained/MobileNetV3_large_x1_0_pretrained.pdparams"
  output_dir: ./output_finetune/
  device: gpu
  save_interval: 50
  eval_during_train: True
  eval_interval: 1
  epochs: 150
  print_batch_step: 10
  use_visualdl: False
  image_shape: [3, 224, 224]
  save_inference_dir: ./inference_finetune

# model architecture
Arch:
  name: MobileNetV3_large_x1_0
  class_num: 4
 
# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
  Eval:
    - CELoss:
        weight: 1.0

Metric:
  Train:
    - TopkAcc:
        topk: [1, 5]
  Eval:
    - TopkAcc:
        topk: [1, 5]

Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Cosine
    learning_rate: 0.0001
    warmup_epoch: 2
  regularizer:
    name: 'L2'
    coeff: 0.00002

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: ImageNetDataset
      image_root: E:/Prototype/PaddleClas/Sports_Clas_data/
      cls_label_path: E:/Prototype/PaddleClas/Sports_Clas_data/train_list.txt
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - RandCropImage:
            size: 224
        - RandFlipImage:
            flip_code: 1
        - AutoAugment:
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''

    sampler:
      name: DistributedBatchSampler
      batch_size: 32
      drop_last: False
      shuffle: True
    loader:
      num_workers: 2
      use_shared_memory: True

  Eval:
    dataset: 
      name: ImageNetDataset
      image_root: E:/Prototype/PaddleClas/Sports_Clas_data/
      cls_label_path: E:/Prototype/PaddleClas/Sports_Clas_data/val_list.txt
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - ResizeImage:
            resize_short: 256
        - CropImage:
            size: 224
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
    sampler:
      name: DistributedBatchSampler
      batch_size: 32
      drop_last: False
      shuffle: False
    loader:
      num_workers: 2
      use_shared_memory: True
